<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllProducts()
    {
        $qb = $this->createQueryBuilder('qb')
            ->select(
                'qb.id',
                'qb.name',
                'qb.category',
                'qb.manufacturer'
            )
        ;

        return $qb
            ->getQuery()
            ->getResult();
    }
}
